[package]
name = "dmz"
version = "0.2.1"
authors = ["Stephen Dolan <stephen.dolan@cl.cam.ac.uk>, Sophia Gold <sophiagoldnyc@gmail.com>"]

[dependencies]
libc = "0.2.0"
cty = "0.2"

[lib]
name = "dmz"
crate-type = ["rlib"]

