[package]
name = "dmz-customized"
version = "0.1.0"
authors = ["Bruno Deferrari <utizoc@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dmz = { path = "../our_dmz/core" }
lazy_static = "1.4"
cty = "0.2"